### ISSUE TITLE
Error: Module build failed

### ISSUE THREAD

**Issue by MiguelGonzalezAravena** [jfcere/ngx-malihu-scrollbar#14]
I follow all step and when i want to use the script, give me this error:

```
Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/observatoriotui/Git/observatorio-tui-app/node_modules/ngx-malihu-scrollbar/index.js'
    at Error (native)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:133087:7)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.440 (http://localhost:8100/build/main.js:1961:80)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.437 (http://localhost:8100/build/main.js:1909:70)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
    at http://localhost:8100/build/main.js:1:1
```

What can i do?

**Comment by jfcere** [comment]
Hi @MiguelGonzalezAravena,

Could you please update to v1.2.0 and tell me if you still have the error?

**Comment by jfcere** [comment]
Closing for no response after 16 days.
Feel free to reopen if you are still having some issue.
